//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   sampler2D colorSampler;
//   float2 g_TexelSize;
//   float g_blurRadiusPixels;
//   float4 g_cameraPos;
//   float g_dofBlend;
//   float g_focalDistanceMeters;
//   float g_maxBlurDistanceMeters;
//   float g_positionRange;
//   sampler2D positionSampler;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   g_TexelSize             c0       1
//   g_cameraPos             c1       1
//   g_focalDistanceMeters   c2       1
//   g_maxBlurDistanceMeters c3       1
//   g_blurRadiusPixels      c4       1
//   g_positionRange         c5       1
//   g_dofBlend              c6       1
//   colorSampler            s0       1
//   positionSampler         s1       1
//

    ps_3_0
    def c7, 0.5, 2, -1, 0
    def c8, -9.99999975e-005, 9.99999975e-005, -0.200000003, -0.400000006
    def c9, -0.600000024, 3, -0.800000012, 4
    def c10, 5, 0, 0, 0
    defi i0, 255, 0, 0, 0
    dcl_texcoord v0.xy  // uv<0,1>
    dcl_2d s0
    dcl_2d s1

#line 100 "C:\Users\bibindon\source\repos\bibindon\RedFortressRender\Render\shader\PostEffectDepthOfField.fx"
    mov r0.xw, c7
    mul r0.xy, r0.x, c0
    add r0.xy, r0, v0  // ::sampleUv<0,1>

#line 116
    texld r1, r0, s0  // ::baseColor<0,1,2,3>

#line 119
    nop
    mov r0.xy, r0  // GetDistanceMeters::uv<0,1>

#line 55
    nop
    mov r0.xy, r0  // DecodeWorldPosition::uv<0,1>

#line 47
    add r2.xy, r0, c0  // ::positionUv<0,1>
    texld r2, r2, s1  // ::encoded<0,1,2,3>
    mul r2.xyz, r2, c7.y
    add r2.xyz, r2, c7.z
    mul r3.yzw, r2.xxyz, c5.x  // ::worldPos<0,1,2>
    mov r3.yzw, r3  // ::DecodeWorldPosition<0,1,2>
    mov r3.x, r2.w  // ::DecodeWorldPosition<3>

#line 55
    mov r3, r3  // ::worldPos<3,0,1,2>
    mov r3.x, r3.x  // GetDistanceMeters::valid<0>
    mov r2.xyz, -c1
    add r2.xyz, r2, r3.yzww
    dp3 r0.z, r2, r2
    rsq r0.z, r0.z
    rcp r0.z, r0.z  // ::centerDistanceMeters<0>

#line 119
    mov r3.x, r3.x  // ::centerValid<0>
    mov r2.x, -r3.x
    add r2.x, r2.x, c7.w
    cmp r2.x, r2.x, c7_abs.z, c7_abs.w
    if_ne r2.x, -r2.x
      mov r3, r1  // ::PS<0,1,2,3>
    else
      mov r3, c7.w
      mov r3, r3  // ::PS<0,1,2,3>
    endif
    if_ne r2.x, -r2.x

#line 159
    else

#line 125
      nop
      mov r0.z, r0.z  // GetBlurHalfSize::distanceMeters<0>

#line 62
      mov r2.x, -c3.x
      add r2.x, r2.x, c2.x
      mov r4.x, c3.x  // ::g_maxBlurDistanceMeters<0>
      cmp r2.x, r2.x, r4.x, c2.x  // ::nearDistance<0>
      mov r2.y, -c3.x
      add r2.y, r2.y, c2.x
      cmp r2.y, r2.y, c2.x, r4.x  // ::farDistance<0>
      mov r2.z, -r2.x
      add r2.y, r2.z, r2.y
      add r2.z, r2.y, c8.x
      cmp r2.y, r2.z, r2.y, c8.y  // ::totalRange<0>
      mov r2.z, -r2.x
      add r2.z, r0.z, r2.z
      rcp r2.y, r2.y
      mul r2.y, r2.y, r2.z
      add r2.z, r2.y, -c7.w
      cmp r2.y, r2.z, r2.y, c7.w
      add r2.z, r2.y, c7.z
      cmp r2.y, r2.z, -c7.z, r2.y  // ::normalized<0>
      mov r0.z, -r0.z
      add r0.z, r0.z, r2.x
      cmp r0.z, r0.z, c7_abs.z, c7_abs.w

#line 72
      if_ne r0.z, -r0.z

#line 92
        mov r2.x, c7.w  // ::GetBlurHalfSize<0>
      else

#line 72
        add r0.z, r2.y, c8.z
        cmp r0.z, r0.z, c7_abs.w, c7_abs.z  // ::GetBlurHalfSize<0>

#line 77
        if_ne r0.z, -r0.z

#line 92
          mov r2.x, -c7.z  // ::GetBlurHalfSize<0>
        else

#line 77
          add r0.z, r2.y, c8.w
          cmp r0.z, r0.z, c7_abs.w, c7_abs.z
          if_ne r0.z, -r0.z

#line 80
            mov r2.x, c7.y  // ::GetBlurHalfSize<0>
          else
            mov r2.x, c7.w  // ::GetBlurHalfSize<0>
          endif
          if_ne r0.z, -r0.z

#line 92
          else

#line 82
            add r0.z, r2.y, c9.x
            cmp r0.z, r0.z, c7_abs.w, c7_abs.z
            if_ne r0.z, -r0.z

#line 85
              mov r2.x, c9.y  // ::GetBlurHalfSize<0>
            endif
            if_ne r0.z, -r0.z

#line 92
            else

#line 87
              add r0.z, r2.y, c9.z
              cmp r0.z, r0.z, c7_abs.w, c7_abs.z
              if_ne r0.z, -r0.z

#line 90
                mov r2.x, c9.w  // ::GetBlurHalfSize<0>
              endif
              if_ne r0.z, -r0.z
              else
                mov r2.x, c10.x  // ::GetBlurHalfSize<0>
              endif
            endif
          endif
        endif
      endif

#line 125
      mov r2.x, r2.x  // ::blurHalfSize<0>
      mov r0.z, -r2.x
      add r0.z, r0.z, c7.w
      cmp r0.z, r0.z, c7_abs.z, c7_abs.w
      if_ne r0.z, -r0.z
        mov r3, r1  // ::PS<0,1,2,3>
      endif
      if_ne r0.z, -r0.z

#line 159
      else

#line 131
        mov r1, r1  // ::sumColor<0,1,2,3>
        mov r0.z, -c7.z  // ::weightSum<0>

#line 135
        mov r2.y, -r2.x  // ::y<0>
        mov r4, r1  // ::sumColor<0,1,2,3>
        mov r2.z, r0.z  // ::weightSum<0>
        mov r2.w, r2.y  // ::y<0>
        rep i0
          mov r5.x, -r2.w
          add r5.x, r2.x, r5.x
          cmp r5.x, r5.x, c7_abs.z, c7_abs.w
          mov r5.y, -r5.x
          mov r5.x, -r5.x
          add r5.x, r5.x, r5.y
          cmp r5.x, r5.x, c7_abs.z, c7_abs.w
          break_ne r5.x, -r5.x

#line 138
          mov r5.x, -r2.x  // ::x<0>
          mov r6, r4  // ::sumColor<0,1,2,3>
          mov r5.y, r2.z  // ::weightSum<0>
          mov r5.z, r5.x  // ::x<0>
          rep i0
            mov r5.w, -r5.z
            add r5.w, r2.x, r5.w
            cmp r5.w, r5.w, c7_abs.z, c7_abs.w
            mov r7.x, -r5.w
            mov r5.w, -r5.w
            add r5.w, r5.w, r7.x
            cmp r5.w, r5.w, c7_abs.z, c7_abs.w
            break_ne r5.w, -r5.w
            add r5.w, r5.z, -c7.w
            abs r5.w, r5.w
            mov r7.x, -r5.w
            mov r5.w, -r5.w
            add r5.w, r5.w, r7.x
            cmp r5.w, r5.w, c7_abs.z, c7_abs.w
            add r7.x, r2.w, -c7.w
            abs r7.x, r7.x
            mov r7.y, -r7.x
            mov r7.x, -r7.x
            add r7.x, r7.x, r7.y
            cmp r7.x, r7.x, c7_abs.z, c7_abs.w
            mul r5.w, r5.w, r7.x
            if_ne r5.w, -r5.w
              add r5.z, r5.z, -c7.z  // ::x<0>

#line 143
            endif
            if_ne r5.w, -r5.w

#line 149
            else

#line 145
              add r7.x, r5.z, -c7.w
              add r7.x, r7.x, c7.w
              mov r7.y, r2.w
              mul r7.xy, r7, c0
              mul r7.xy, r7, c4.x  // ::offset<0,1>
              add r7.xy, r0, r7  // ::tapUv<0,1>
              mov r7.zw, c7.w
              texldl r7, r7, s0
              add r6, r6, r7  // ::sumColor<0,1,2,3>
              add r5.y, r5.y, -c7.z  // ::weightSum<0>
            endif
            add r5.w, r5.w, r5.w
            mov r7.x, -r5.w
            mov r5.w, -r5.w
            add r5.w, r5.w, r7.x
            cmp r5.w, r5.w, c7_abs.w, c7_abs.z

#line 138
            if_ne r5.w, -r5.w
            else
              add r5.w, r5.z, -c7.w
              add r5.w, r5.w, c7.w
              add r5.z, r5.w, -c7.z  // ::x<0>
            endif

#line 150
          endrep
          mov r4, r6  // ::sumColor<0,1,2,3>
          mov r2.z, r5.y  // ::weightSum<0>

#line 135
          add r2.w, r2.w, -c7.z  // ::y<0>

#line 151
        endrep
        mov r0.x, -r2.z
        add r0.x, r0.x, c7.w
        cmp r0.x, r0.x, c7_abs.z, c7_abs.w
        if_ne r0.x, -r0.x
          mov r3, r1  // ::PS<0,1,2,3>
        endif
        if_ne r0.x, -r0.x
        else
          rcp r5.x, r2.z
          rcp r5.y, r2.z
          rcp r5.z, r2.z
          rcp r5.w, r2.z
          mul r2, r4, r5  // ::blurredColor<0,1,2,3>
          add r0.x, -r0.w, c6.x
          cmp r0.x, r0.x, c6.x, r0.w
          add r0.y, r0.x, c7.z
          cmp r0.x, r0.y, -c7.z, r0.x
          mov r4, -r1
          add r2, r2, r4
          mul r0, r0.x, r2
          add r3, r0, r1  // ::PS<0,1,2,3>
        endif
      endif
    endif

#line 97
    mov oC0, r3  // ::PS<0,1,2,3>

// approximately 244 instruction slots used (4 texture, 240 arithmetic)
